import { buttonTextSizes, buttonTypes, buttonColors } from '_shared.js'
export const attention = {
  base: 'border-2 relative flex items-start',
  tooltip: 'i-bg-$color-tooltip-background i-border-$color-tooltip-background i-shadow-$shadow-tooltip i-text-$color-tooltip-text rounded-4 py-6 px-8',
  callout: 'i-bg-$color-callout-background i-border-$color-callout-border i-text-$color-callout-text py-8 px-16 rounded-8',
  highlight: 'i-bg-$color-callout-background i-border-$color-callout-border i-text-$color-callout-text py-8 px-16 rounded-8 drop-shadow-m',
  popover: 'i-bg-$color-popover-background i-border-$color-popover-background i-text-$color-popover-paragraph-text rounded-8 p-16 drop-shadow-m',
  arrowBase: 'absolute h-[14px] w-[14px] border-2 border-b-0 border-r-0 rounded-tl-4 transform',
  arrowDirectionLeft: '-left-[8px]',
  arrowDirectionRight: '-right-[8px]',
  arrowDirectionBottom: '-bottom-[8px]',
  arrowDirectionTop: '-top-[8px]',
  arrowTooltip: 'i-bg-$color-tooltip-background i-border-$color-tooltip-background',
  arrowCallout: 'i-bg-$color-callout-background i-border-$color-callout-border',
  arrowPopover: 'i-bg-$color-popover-background i-border-$color-popover-background',
  arrowHighlight: 'i-bg-$color-callout-background i-border-$color-callout-border',
  content: 'last-child:mb-0',
  notCallout: 'absolute z-50',
  closeBtn: `${buttonTextSizes.medium} ${buttonTypes.pill} ${buttonColors.pill} justify-self-end -mr-8 ml-8`,
};
