---
token: defs

# TODO: font-size, line-height, shadows, colors and all other common things should live in a common.css rather than brand.css.

transparent: transparent
inherit: inherit
none: none

# values are in pixels, but they render by default as rems. Using `usePixels=true` flag in @warp-ds/uno forces them to pixels.
font:
  size:
    xs: 1.2rem
    s: 1.4rem
    m: 1.6rem
    ml: 2rem
    l: 2.2rem
    xl: 2.8rem
    xxl: 3.4rem
    xxxl: 4.8rem
  family: 'BlocketSans, sans-serif'
line:
  height:
    xs: 1.6rem
    s: 2rem
    m: 2.4rem
    ml: 2.8rem
    l: 2.8rem
    xl: 3.6rem
    xxl: 4rem
    xxxl: 5.6rem
